# Generated by Django 4.1.7 on 2024-01-13 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('about', models.CharField(max_length=1000)),
                ('website', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('creation_date', models.CharField(max_length=100)),
                ('materials_used', models.CharField(max_length=200)),
                ('dimensions', models.CharField(max_length=150)),
                ('listing_start', models.DateField(max_length=100)),
                ('listing_end', models.DateField(max_length=100)),
                ('current_price', models.IntegerField(default=0)),
                ('starting_price', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, upload_to='item_images/')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.creator')),
            ],
        ),
    ]
