# Generated by Django 4.1.7 on 2024-01-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='role',
            field=models.CharField(choices=[('A', 'Artist'), ('D', 'Designer'), ('C', 'Company')], default=1, max_length=50, verbose_name='Role'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('PA', 'Painting'), ('WA', 'Wall Art'), ('PR', 'Prints'), ('G', 'Goods')], default=1, max_length=50, verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='items'),
        ),
    ]
