# Generated by Django 4.1.7 on 2024-01-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='time',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
