# Generated by Django 4.1.7 on 2024-01-24 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_bid_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='time',
        ),
    ]
