# Generated by Django 4.1.7 on 2024-01-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_creator_role_item_category_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='role',
            field=models.CharField(choices=[('A', 'Artist'), ('D', 'Designer'), ('C', 'Company')], max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('PA', 'Painting'), ('WA', 'Wall Art'), ('PR', 'Prints'), ('G', 'Goods')], max_length=50),
        ),
    ]
