# Generated by Django 4.1.7 on 2024-01-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_creator_role_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='about',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
