# Generated by Django 4.1.7 on 2024-01-24 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_bid_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
