# Generated by Django 5.0.1 on 2024-01-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_bid_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('painting', 'Painting'), ('wallart', 'Wall Art'), ('prints', 'Prints'), ('objects', 'Objects'), ('goods', 'Goods')], max_length=9),
        ),
    ]
