# Generated by Django 4.1.7 on 2024-01-13 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_creator_about_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='listing_end',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='listing_start',
            field=models.DateField(max_length=50),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amoun', models.IntegerField(max_length=50)),
                ('bidder', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='inventory.item')),
            ],
        ),
    ]
