# Generated by Django 4.1.7 on 2024-01-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_item_listing_end_alter_item_listing_start_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='amoun',
        ),
        migrations.AddField(
            model_name='bid',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bid',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='bid',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='creator',
            name='role',
            field=models.CharField(choices=[('A', 'Artist'), ('D', 'Designer'), ('C', 'Company')], max_length=1),
        ),
        migrations.AlterField(
            model_name='creator',
            name='website',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('PA', 'Painting'), ('WA', 'Wall Art'), ('PR', 'Prints'), ('O', 'Objects'), ('G', 'Goods')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='listing_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='listing_start',
            field=models.DateField(),
        ),
    ]
