# Generated by Django 5.0.1 on 2024-01-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='role',
            field=models.CharField(choices=[('artist', 'Artist'), ('designer', 'Designer'), ('company', 'Company')], max_length=8),
        ),
    ]
