# Generated by Django 4.1.7 on 2024-01-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_creator_role_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='role',
            field=models.CharField(choices=[('Artist', 'Artist'), ('Designer', 'Designer'), ('Company', 'Company')], max_length=8),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Painting', 'Painting'), ('Wall Art', 'Wall Art'), ('Prints', 'Prints'), ('Objects', 'Objects'), ('Goods', 'Goods')], max_length=9),
        ),
    ]
