# Generated by Django 4.1.7 on 2024-01-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_creator_role_alter_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bidder',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='phone_number',
        ),
    ]
