# Generated by Django 4.1.7 on 2024-01-19 21:13

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_bid_bidder_remove_bid_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('poster', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=inventory.models.upload_to)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
